///////////////////////////////////////////////////////////
//  CostStadistic.cs
//  Implementation of the Class CostStadistic
//  Generated by Enterprise Architect
//  Created on:      21-May-2010 05:30:32 p.m.
///////////////////////////////////////////////////////////




using SolucionAlumno;
namespace SolucionAlumno {
	/// <summary>
	/// This class implements the algorithm using the Strategy interface.
	/// </summary>
	public class CostStadistic : CostCalculatorStrategy {

		public CostStadistic(){

		}

		~CostStadistic(){

		}

		public override void Dispose(){

		}

		/// 
		/// <param name="start"></param>
		/// <param name="actual"></param>
		/// <param name="goal"></param>
		public int aproximateMove(Point start, Point actual, Point goal){

			return 0;
		}

		/// 
		/// <param name="previousNode"></param>
		/// <param name="actual"></param>
		public int move(Node previousNode, Node actual){

			return 0;
		}

	}//end CostStadistic

}//end namespace Sistema